package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;
import static frc.robot.constants.FieldConstants.*;
import static frc.robot.constants.SubsystemConstants.DrivetrainConstants.*;
import static frc.robot.constants.VisionConstants.*;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.FieldCentric;
import com.ctre.phoenix6.swerve.SwerveRequest.FieldCentricFacingAngle;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import dev.doglog.DogLog;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.ConditionalCommand;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Robot;
import frc.robot.Vision;
import frc.robot.constants.TunerConstants;
import frc.robot.constants.TunerConstants.TunerSwerveDrivetrain;

import java.util.Optional;
import java.util.function.BooleanSupplier;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  PIDController drivePID = new PIDController(DRIVE_P, DRIVE_I, DRIVE_D);
  // Pose2d[] trenchPoses = LEFT_OUT;
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;
  private double hubDistance = 0;
  Vision cameraA = new Vision(this::addVisionMeasurement, CAMERA_A, CAMERA_A_TRANSFORM);
  Vision cameraB = new Vision(this::addVisionMeasurement, CAMERA_B, CAMERA_B_TRANSFORM);
  Vision cameraC = new Vision(this::addVisionMeasurement, CAMERA_C, CAMERA_C_TRANSFORM);
  Vision cameraD = new Vision(this::addVisionMeasurement, CAMERA_D, CAMERA_D_TRANSFORM);
  Vision[] cameras = { cameraA, cameraB, cameraC, cameraD };
  Rotation2d desriedAngle = Rotation2d.kZero;

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

  /* Swerve requests to apply during SysId characterization */
  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

  /*
   * SysId routine for characterizing translation. This is used to find PID gains
   * for the drive motors.
   */
  private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
      new SysIdRoutine.Config(
          null, // Use default ramp rate (1 V/s)
          Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
          null, // Use default timeout (10 s)
          // Log state with SignalLogger class
          state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
      new SysIdRoutine.Mechanism(
          output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  /*
   * SysId routine for characterizing steer. This is used to find PID gains for
   * the steer motors.
   */
  @SuppressWarnings("unused")
  private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
      new SysIdRoutine.Config(
          null, // Use default ramp rate (1 V/s)
          Volts.of(7), // Use dynamic voltage of 7 V
          null, // Use default timeout (10 s)
          // Log state with SignalLogger class
          state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
      new SysIdRoutine.Mechanism(
          volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

  /*
   * SysId routine for characterizing rotation.
   * This is used to find PID gains for the FieldCentricFacingAngle
   * HeadingController.
   * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
   * importing the log to SysId.
   */
  @SuppressWarnings("unused")
  private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
      new SysIdRoutine.Config(
          /* This is in radians per second², but SysId only supports "volts per second" */
          Volts.of(Math.PI / 6).per(Second),
          /* This is in radians per second, but SysId only supports "volts" */
          Volts.of(Math.PI),
          null, // Use default timeout (10 s)
          // Log state with SignalLogger class
          state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
      new SysIdRoutine.Mechanism(
          output -> {
            /* output is actually radians per second, but SysId only supports "volts" */
            setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
            /* also log the requested output for SysId */
            SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
          },
          null,
          this));

  /* The SysId routine to test */
  private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>
   * This constructs the underlying hardware devices, so users should not
   * construct the devices
   * themselves. If they need the devices, they can access them through getters in
   * the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules             Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    initPathplanner();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>
   * This constructs the underlying hardware devices, so users should not
   * construct the devices
   * themselves. If they need the devices, they can access them through getters in
   * the classes.
   *
   * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If
   *                                unspecified or set to
   *                                0 Hz, this is 250 Hz on CAN FD, and 100 Hz on
   *                                CAN 2.0.
   * @param modules                 Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    initPathplanner();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>
   * This constructs the underlying hardware devices, so users should not
   * construct the devices
   * themselves. If they need the devices, they can access them through getters in
   * the classes.
   *
   * @param drivetrainConstants       Drivetrain-wide constants for the swerve
   *                                  drive
   * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
   *                                  unspecified or set to
   *                                  0 Hz, this is 250 Hz on CAN FD, and 100 Hz
   *                                  on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry
   *                                  calculation in the form
   *                                  [x, y, theta]ᵀ, with units in meters and
   *                                  radians
   * @param visionStandardDeviation   The standard deviation for vision
   *                                  calculation in the form [x, y,
   *                                  theta]ᵀ, with units in meters and radians
   * @param modules                   Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    initPathplanner();
  }

  public void initPathplanner() {
    // massKG = 68.4 assuming max weight
    // MOI is gotten from CAD, hopefully today,
    // ModuleConfig moduleConfic = new ModuleConfig(2in, MAX_SPEED, 1.1/*COF*/,
    // DCMotor.krakenX60,
    // 1))
    // TunerConstants...
    Translation2d[] moduleOffsets = new Translation2d[] {
        new Translation2d(TunerConstants.FrontLeft.LocationX, TunerConstants.FrontLeft.LocationY),
        new Translation2d(
            TunerConstants.FrontRight.LocationX, TunerConstants.FrontRight.LocationY),
        new Translation2d(TunerConstants.BackLeft.LocationX, TunerConstants.BackLeft.LocationY),
        new Translation2d(TunerConstants.BackRight.LocationX, TunerConstants.BackRight.LocationY)
    };
    RobotConfig config = new RobotConfig(ROBOT_MASS_KG, WHEEL_COF, MODULE_CONFIG, moduleOffsets);

    AutoBuilder.configure(
        () -> getState().Pose,
        this::resetPose,
        () -> getState().Speeds,
        (speeds, feedforwards) -> setControl(
            m_pathApplyRobotSpeeds
                .withSpeeds(speeds)
                .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
        new PPHolonomicDriveController(
            new PIDConstants(DRIVE_P, DRIVE_I, DRIVE_D), // TODO: tune these drive pid constants
            new PIDConstants(
                ROTATION_P, ROTATION_I, ROTATION_D)
        ),
        config,
        () -> {
          var alliance = DriverStation.getAlliance();
          if (alliance.isPresent()) {
            return alliance.get() == DriverStation.Alliance.Red;
          }
          return false;
        },
        this);
  }

  /**
   * Returns a command that applies the specified control request to this swerve
   * drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  public BooleanSupplier isInAllianceZone() {
    return (DriverStation.getAlliance().isPresent() && DriverStation.getAlliance().get() == DriverStation.Alliance.Red
        ? () -> {
          return getState().Pose.getX() > FIELD_LENGTH_M - Units.inchesToMeters(158.5);
        }
        : () -> {
          return getState().Pose.getX() < Units.inchesToMeters(158.5);
        });
  }

  public BooleanSupplier isNotInAllianceZone() {
    return (DriverStation.getAlliance().isPresent() && DriverStation.getAlliance().get() == DriverStation.Alliance.Red
        ? () -> {
          return !(getState().Pose.getX() > FIELD_LENGTH_M - Units.inchesToMeters(158.5));
        }
        : () -> {
          return !(getState().Pose.getX() < Units.inchesToMeters(158.5));
        });
  }

  public BooleanSupplier isInOpposingAllianceZone() {
    return (!(DriverStation.getAlliance().isPresent() && DriverStation.getAlliance().get() == DriverStation.Alliance.Red)
    ? () -> {
      return getState().Pose.getX() > FIELD_LENGTH_M - Units.inchesToMeters(158.5);
    }
    : () -> {
      return getState().Pose.getX() < Units.inchesToMeters(158.5);
    });
  }

  public Command joystickDrive(
      DoubleSupplier joystickX, DoubleSupplier joystickY, DoubleSupplier joystickThetaX) {
    FieldCentric request = new SwerveRequest.FieldCentric()
        .withDeadband(0.0)
        .withRotationalDeadband(0.0)
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage);
    return run(
        () -> this.setControl(
            request
                .withVelocityX(-joystickY.getAsDouble() * MAX_DRIVE_SPEED)
                .withVelocityY(-joystickX.getAsDouble() * MAX_DRIVE_SPEED)
                .withRotationalRate(-joystickThetaX.getAsDouble() * MAX_ROTATIONAL_SPEED)))
        .withName("Joystick Drive");
  }

  public Command pointTowardsPoint(
      Supplier<Translation2d> desiredPoint, DoubleSupplier joystickX, DoubleSupplier joystickY) {
    FieldCentricFacingAngle request = new SwerveRequest.FieldCentricFacingAngle()
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
        .withDeadband(MAX_DRIVE_SPEED * 0.01)
        .withRotationalDeadband(MAX_ROTATIONAL_SPEED * 0.01);
    request.withHeadingPID(ROTATION_P, ROTATION_I, ROTATION_D);

    return defer(
        () -> run(() -> {
          Translation2d delta = desiredPoint.get().minus(getState().Pose.getTranslation());

          Rotation2d targetAngle = delta.getAngle().plus(isRedSide() ? Rotation2d.k180deg : Rotation2d.kZero);
          desriedAngle = targetAngle;
          this.setControl(
              request
                  .withVelocityX(-joystickY.getAsDouble() * MAX_DRIVE_SPEED)
                  .withVelocityY(-joystickX.getAsDouble() * MAX_DRIVE_SPEED)
                  .withTargetDirection(targetAngle));
        }));
  }

  public Command pidToPoint(Pose2d pose) {
    FieldCentricFacingAngle request = new SwerveRequest.FieldCentricFacingAngle()
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
        .withHeadingPID(ROTATION_P, ROTATION_I, ROTATION_D);

    return run(
        () -> {
          double velX = drivePID.calculate(pose.getX(), getState().Pose.getX());
          double velY = drivePID.calculate(pose.getY(), getState().Pose.getY());

          this.setControl(
              request
                  .withVelocityX(velX)
                  .withVelocityY(velY)
                  .withTargetDirection(pose.getRotation().plus(Rotation2d.k180deg)));
        });
  }

  public Pose2d whereShoot() {
    if (getState().Pose.getY() > Units.inchesToMeters(158.5)
        && getState().Pose.getY() < FIELD_LENGTH_M - Units.inchesToMeters(158.5)) {
      return getState().Pose.nearest(getShuttlePoses());
    } else {
      return getHubLocation();
    }
  }

   public boolean isAtDesiredAngle() {
    Rotation2d checkAngle = desriedAngle;
    if(isRedSide()) {
      checkAngle = checkAngle.plus(Rotation2d.fromDegrees(180));
    }
    return (Math.abs(getState().Pose.getRotation().minus(checkAngle).getDegrees()) < 7);
   }

   public BooleanSupplier isAtDesiredAngleCheck() {
    return () -> isAtDesiredAngle();
   }

   /**
    * Runs the SysId Quasistatic test in the given direction for the routine
    * specified by {@link
    * #m_sysIdRoutineToApply}.
    *
    * @param direction Direction of the SysId Quasistatic test
    * @return Command to run
    */
    
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  public Command resetThePose(Pose2d resetPose) {
    return runOnce(() -> {
      resetPose(resetPose);
    });
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified
   * by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

  public DoubleSupplier getChangeInHubDistance() {
    return () -> getState().Pose.getTranslation().getDistance(getHubLocation().getTranslation()) - hubDistance;
  }

  public DoubleSupplier getVelocityY() {
    return () -> ChassisSpeeds.fromRobotRelativeSpeeds(getState().Speeds, getState().Pose.getRotation()).vyMetersPerSecond;
  }
  public DoubleSupplier getVelocityX() {
    return () -> ChassisSpeeds.fromRobotRelativeSpeeds(getState().Speeds, getState().Pose.getRotation()).vxMetersPerSecond;
  }

  @Override
  public void periodic() {
    // mine
    hubDistance = getState().Pose.getTranslation().getDistance(getHubLocation().getTranslation());
    DogLog.log("Subsystems/Drive/Pose", getState().Pose);
    // DogLog.log("Subsystems/Drive/HubPose", getHubLocation());
    DogLog.log("Subsystems/Drive/HubDistance", hubDistance);
    // if (getCurrentCommand() != null) {
    //   DogLog.log("Subsystems/Drive/CurrentCommand", getCurrentCommand().getName());
    // } else {
    //   DogLog.log("Subsystems/Drive/CurrentCommand", "None");
    // }
    DogLog.log("Subsystems/Drive/isInAllianceZone", isInAllianceZone().getAsBoolean());

    // DogLog.log("Subsystems/Drive/Speeds", getState().Speeds);
    if (!Robot.isReal()) {
      for (Vision camera : cameras) {
        camera.simulationPeriodic(getState().Pose);
      }
    }

    for (Vision camera : cameras) {
      camera.periodic();
    }

    for (int i = 0; i < 4; i++) {
      DogLog.log("Subsystems/Drive/Current" + i,
          getModule(i).getDriveMotor().getTorqueCurrent(true).getValueAsDouble());
    }
    DogLog.log("Subsystems/Drive/Checks", isAtDesiredAngleCheck().getAsBoolean());
    // not mine
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply
     * it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts
     * mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is
     * disabled.
     * This ensures driving behavior doesn't change until an explicit disable event
     * occurs during testing.
     */
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier = new Notifier(
        () -> {
          final double currentTime = Utils.getCurrentTimeSeconds();
          double deltaTime = currentTime - m_lastSimTime;
          m_lastSimTime = currentTime;

          /* use the measured time delta, get battery voltage from WPILib */
          updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the
   * odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision
   *                              camera.
   * @param timestampSeconds      The timestamp of the vision measurement in
   *                              seconds.
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the
   * odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>
   * Note that the vision measurement standard deviations passed into this method
   * will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters    The pose of the robot as measured by the
   *                                 vision camera.
   * @param timestampSeconds         The timestamp of the vision measurement in
   *                                 seconds.
   * @param visionMeasurementStdDevs Standard deviations of the vision pose
   *                                 measurement in the form
   *                                 [x, y, theta]ᵀ, with units in meters and
   *                                 radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds.
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is
   *         empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
}
