// spotless:off
package frc.robot.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;



/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj across_The_Bumb = new ChoreoTraj(
        "across_The_Bumb",
        OptionalInt.empty(),
        4.60371,
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266)),
        new Pose2d(3.02274, 5.46798, Rotation2d.fromRadians(-0.7854))
    );
    public static final ChoreoTraj Depauto_Start = new ChoreoTraj(
        "Depauto_Start",
        OptionalInt.empty(),
        5.13622,
        new Pose2d(4.4, 0.45, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2, 1, Rotation2d.fromRadians(0.85922))
    );
    public static final ChoreoTraj Depot = new ChoreoTraj(
        "Depot",
        OptionalInt.empty(),
        2.34771,
        new Pose2d(2, 1, Rotation2d.fromRadians(0)),
        new Pose2d(2, 1, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj Depot_copy1 = new ChoreoTraj(
        "Depot_copy1",
        OptionalInt.empty(),
        2.40494,
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266)),
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266))
    );
    public static final ChoreoTraj Fist_Bump = new ChoreoTraj(
        "Fist_Bump",
        OptionalInt.empty(),
        4.66256,
        new Pose2d(8.5, 5.9, Rotation2d.fromRadians(0.7854)),
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266))
    );
    public static final ChoreoTraj Fist_My_Bump = new ChoreoTraj(
        "Fist_My_Bump",
        OptionalInt.empty(),
        3.03482,
        new Pose2d(4.39911, 0.47, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(8.5, 5.9, Rotation2d.fromRadians(0.7854))
    );
    public static final ChoreoTraj IDk_what_to_call_this = new ChoreoTraj(
        "IDk_what_to_call_this",
        OptionalInt.empty(),
        8.70057,
        new Pose2d(4.41148, 0.76028, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266))
    );
    public static final ChoreoTraj NewPath_copy1 = new ChoreoTraj(
        "NewPath_copy1",
        OptionalInt.empty(),
        3.67858,
        new Pose2d(3.2, 0.9, Rotation2d.fromRadians(1.13446)),
        new Pose2d(3.07248, 5.47165, Rotation2d.fromRadians(-0.75159))
    );
    public static final ChoreoTraj NewPath_copy2 = new ChoreoTraj(
        "NewPath_copy2",
        OptionalInt.empty(),
        3.37545,
        new Pose2d(3.2, 0.9, Rotation2d.fromRadians(1.13446)),
        new Pose2d(3.2, 0.9, Rotation2d.fromRadians(1.13446))
    );
    public static final ChoreoTraj New_depot = new ChoreoTraj(
        "New_depot",
        OptionalInt.empty(),
        2.90351,
        new Pose2d(2, 1, Rotation2d.fromRadians(0)),
        new Pose2d(2, 1, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj New_Right_Start = new ChoreoTraj(
        "New_Right_Start",
        OptionalInt.empty(),
        4.50805,
        new Pose2d(4.4, 0.45, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266))
    );
    public static final ChoreoTraj Right_2nd_Path = new ChoreoTraj(
        "Right_2nd_Path",
        OptionalInt.empty(),
        6.15133,
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266)),
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266))
    );
    public static final ChoreoTraj Right_2nd_Path_Far_Bad = new ChoreoTraj(
        "Right_2nd_Path_Far_Bad",
        OptionalInt.empty(),
        5.70183,
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266)),
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266))
    );
    public static final ChoreoTraj Right_2nd_Path_Far_Trench = new ChoreoTraj(
        "Right_2nd_Path_Far_Trench",
        OptionalInt.empty(),
        5.93154,
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266)),
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266))
    );
    public static final ChoreoTraj Right_2nd_Path_shallow = new ChoreoTraj(
        "Right_2nd_Path_shallow",
        OptionalInt.empty(),
        5.25704,
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266)),
        new Pose2d(2.22308, 0.55561, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj Zone_Start = new ChoreoTraj(
        "Zone_Start",
        OptionalInt.empty(),
        5.8793,
        new Pose2d(3.65, 0.4, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2, 1, Rotation2d.fromRadians(0.85219))
    );
    public static final ChoreoTraj Right_2nd_Path_Far = new ChoreoTraj(
        "Right_2nd_Path_Far",
        OptionalInt.empty(),
        4.94956,
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266)),
        new Pose2d(2.4, 1.3, Rotation2d.fromRadians(0.87266))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("across_The_Bumb", across_The_Bumb),
        Map.entry("Depauto_Start", Depauto_Start),
        Map.entry("Depot", Depot),
        Map.entry("Depot_copy1", Depot_copy1),
        Map.entry("Fist_Bump", Fist_Bump),
        Map.entry("Fist_My_Bump", Fist_My_Bump),
        Map.entry("IDk_what_to_call_this", IDk_what_to_call_this),
        Map.entry("NewPath_copy1", NewPath_copy1),
        Map.entry("NewPath_copy2", NewPath_copy2),
        Map.entry("New_depot", New_depot),
        Map.entry("New_Right_Start", New_Right_Start),
        Map.entry("Right_2nd_Path", Right_2nd_Path),
        Map.entry("Right_2nd_Path_Far_Bad", Right_2nd_Path_Far_Bad),
        Map.entry("Right_2nd_Path_Far_Trench", Right_2nd_Path_Far_Trench),
        Map.entry("Right_2nd_Path_shallow", Right_2nd_Path_shallow),
        Map.entry("Zone_Start", Zone_Start),
        Map.entry("Right_2nd_Path_Far", Right_2nd_Path_Far)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
}
// spotless:on
